parallel-jobs = 1
remove-rv-integrations-checks = false
# see https://github.com/nvbangg/Patches-APK-Builder/blob/main/CONFIG.md for more detailed explanations

[YouTube]
patches-source = "nvbangg/nvbangg-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "nvbangg"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube-ReVanced]
excluded-patches = "'Custom branding'"
app-name = "youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube-Morphe]
patches-source = "MorpheApp/morphe-patches"
excluded-patches = "'Custom branding'"
cli-source = "MorpheApp/morphe-cli"
app-name = "youtube"
rv-brand = "morphe"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube-Music]
patches-source = "nvbangg/nvbangg-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "nvbangg"
archive-dlurl = "https://archive.org/download/nvbangg-apks/com.google.android.apps.youtube.music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[YouTube-Music-Morphe]
patches-source = "MorpheApp/morphe-patches"
excluded-patches = "'Custom branding'"
cli-source = "MorpheApp/morphe-cli"
app-name = "youtube-music"
rv-brand = "morphe"
archive-dlurl = "https://archive.org/download/nvbangg-apks/com.google.android.apps.youtube.music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[YouTube-Music-ReVanced]
excluded-patches = "'Custom branding'"
app-name = "youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[Google-Photos]
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Instagram]
uptodown-dlurl = "https://instagram.en.uptodown.com/android"

[Messenger]
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"

[TikTok]
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"

[Telegram]
patches-source = "Aunali321/ReVancedExperiments"
rv-brand = "aunali321"
uptodown-dlurl = "https://telegram-google-play-version.en.uptodown.com/android"

[Telegram-Web]
patches-source = "Aunali321/ReVancedExperiments"
rv-brand = "aunali321"
uptodown-dlurl = "https://telegram.en.uptodown.com/android"

[Twitter]
uptodown-dlurl = "https://twitter.en.uptodown.com/android"

[Twitter-Piko]
patches-source = "crimera/piko"
app-name = "twitter"
rv-brand = "crimera"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"

[Prime-Video]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "hoo-dles"
uptodown-dlurl = "https://amazon-video.en.uptodown.com/android"

[Disney]
uptodown-dlurl = "https://disney-disneyplus.en.uptodown.com/android"

[WPS-Office]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "hoo-dles"
uptodown-dlurl = "https://wps-office.en.uptodown.com/android"

[Duolingo]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "hoo-dles"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"

[Cake]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "hoo-dles"
uptodown-dlurl = "https://me-mycake.en.uptodown.com/android"

[Twitch]
uptodown-dlurl = "https://twitch.en.uptodown.com/android"

[Reddit]
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "morphe"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Photomath]
uptodown-dlurl = "https://photomath.en.uptodown.com/android"

[Google-Recorder]
uptodown-dlurl = "https://opnemer.en.uptodown.com/android"

[SoundCloud]
uptodown-dlurl = "https://soundcloud.en.uptodown.com/android"

[Pandora]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pandora/pandora-music-podcasts/"
archive-dlurl = "https://archive.org/download/nvbangg-apks/com.pandora.android/"

[Tumblr]
uptodown-dlurl = "https://tumblr.en.uptodown.com/android"

[Cricbuzz]
uptodown-dlurl = "https://cricbuzz-cricket-scores-and-news.en.uptodown.com/android"

[MyFitnessPal]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "hoo-dles"
uptodown-dlurl = "https://calorie-counter-myfitnesspal.en.uptodown.com/android"

[Strava]
uptodown-dlurl = "https://strava.en.uptodown.com/android"

[Crunchyroll]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "hoo-dles"
uptodown-dlurl = "https://crunchyroll.en.uptodown.com/android"
